#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".
set -e

# Assume CWD is project root aka mindless/...
git diff --cached --name-only | if grep --quiet "server/api/data/Mindless.sql"
then
  hooks/validate_schema.sh || exit 1
fi

git diff --cached --name-only | if grep --quiet "server/database"
then
  hooks/pre-commit_database.sh || exit 1
fi
