#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".
set -e

# TODO: Figure out how to capture output and print it. 
function verify_call {
  eval $1
  status=$?

  if [ $status -ne 0 ];
  then
    echo "Ran \"$1\":"
    echo "Status code is: $status"
    exit $status
  fi
}

cargo_wrap_file="server/scripts/cargo_wrap"

git diff --cached --name-only | if grep --quiet "server"
then
  # Format files
  # Build & Run Tests
  verify_call "$cargo_wrap_file --type 'api' test"
  verify_call "$cargo_wrap_file --type 'database' test"

  # Run Clippy
  verify_call "$cargo_wrap_file --type 'api' clippy"
  verify_call "$cargo_wrap_file --type 'database' clippy"
fi
